kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-discord-bot
  namespace: {{ .Values.namespace }}
data:
  DISCORD_TOKEN: ''
  DISCORD_CLIENT_ID: ''
  GUILD_IDS: ''
  NAMESPACE: '{{ .Values.namespace }}'
  # JSON array of server configurations
  # Example: '[{"id":"valheim","deploymentName":"valheim-deploy","containerName":"valheim","serverName":"My Valheim"}]'
  SERVERS: ''
  JOIN_CODE_LOOP_COUNT: '20'
  JOIN_CODE_LOOP_TIMEOUT_MILLIS: '5000'